site_name: PAI平台文档
site_url: http://127.0.0.1:8000

use_directory_urls: false

  
theme:
  name: "material"
  language: "zh"
  nav_style: "light"
  features:
    - navigation.tabs
    - navigation.indexes
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - .mkdocs/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:

  - 开发语言:
    - Java:
      - 多线程: language/java/muiltthread.md
      - JVM: language/java/jvm.md
      - 集合: language/java/set.md
      
  - 大数据:
    - Spark:
      - 面试题: bigdata/spark/face.md
      - 基础介绍: bigdata/spark/introduce.md
    - HBase:
      - 面试题: bigdata/hbase/face.md
      
  - 云原生:
    - K8S:
      - 安装部署: cloudnative/k8s/deploy.md
    - Fluid: 
      - 入门介绍: cloudnative/fluid/introduce.md
      - 安装部署: cloudnative/fluid/deploy.md
   
  